security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                use_referer: true

            logout:
                path: app_logout
                target: home

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

        - { path: ^/contact/add, roles: ROLE_USER }
        - { path: ^/contact/\d+/edit, roles: ROLE_USER }
        - { path: ^/contact/\d+/delete, roles: ROLE_USER }
